{% set name = "espsim" %}
{% set version = "1.0.0" %}
{% set git_version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hesther/espsim/archive/refs/tags/v{{ git_version }}.tar.gz
  sha256: b381eae851e22d357ed25effe9dc80587fafc6c6cc7159863da9733292a6aabd

  patches:
    # The tagged version upstream did not update the setup.py version to 1.0.0.
    - setup-py.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - rdkit
    - numpy
    - scipy
    - psi4
    - resp

test:
  imports:
    - espsim
  commands:
    - pip check
    - python scripts/test_imports.py
    - python scripts/test_esp_function.py
    - python scripts/test_embedalignscore.py
  requires:
    - pip
  source_files:
    - scripts/

about:
  home: https://github.com/hesther/espsim
  summary: Scoring of shape and ESP similarity with RDKit
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hesther
    - hadim
